version: '3'
services:
  bot:
    build: .
    container_name: bot
    restart: always
    links:
      - mongo_db

  mongo_db:
    image: mongo
    container_name: bot
    restart: always
    volumes:
      - /var/bot/data:/data/db
    ports:
      - 27017:27017
